// <auto-generated />
using System;
using Callendar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Callendar.Migrations
{
    [DbContext(typeof(CallendarDbContext))]
    [Migration("20191124121022_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Callendar.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsWork");

                    b.Property<string>("Name");

                    b.Property<string>("RepresentingColor");

                    b.Property<double>("SalaryPercent");

                    b.HasKey("Id");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("Callendar.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PermissionLevel");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Callendar.TakenAbsence", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("AbsenceId");

                    b.Property<int>("DaysCount");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Id");

                    b.Property<bool>("IsAccepted");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("UserId", "AbsenceId");

                    b.HasIndex("AbsenceId");

                    b.ToTable("TakenAbsences");
                });

            modelBuilder.Entity("Callendar.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsClosed");

                    b.Property<string>("Name");

                    b.Property<int>("TaskCategoryId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TaskCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Callendar.TaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ScorePoints");

                    b.HasKey("Id");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("Callendar.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Callendar.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsLeader");

                    b.Property<string>("LastName");

                    b.Property<int>("PermissionId");

                    b.Property<string>("PhotoPath");

                    b.Property<int>("Points");

                    b.Property<string>("Position");

                    b.Property<int>("TeamId");

                    b.Property<int>("VacationDaysLeft");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Callendar.TakenAbsence", b =>
                {
                    b.HasOne("Callendar.Absence", "Absence")
                        .WithMany("TakenAbsences")
                        .HasForeignKey("AbsenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Callendar.User", "User")
                        .WithMany("TakenAbsences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Callendar.Task", b =>
                {
                    b.HasOne("Callendar.TaskCategory", "TaskCategory")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Callendar.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Callendar.User", b =>
                {
                    b.HasOne("Callendar.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Callendar.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
