// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Callendar.Migrations
{
    [DbContext(typeof(CallendarDbContext))]
    internal class CallendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Callendar.Absence", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<bool>("IsWork");

                b.Property<string>("Name");

                b.Property<string>("RepresentingColor");

                b.Property<double>("SalaryPercent");

                b.HasKey("Id");

                b.ToTable("Absences");
            });

            modelBuilder.Entity("Callendar.Position", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Permissions");
            });

            modelBuilder.Entity("Callendar.TakenAbsence", b =>
            {
                b.Property<Guid>("UserId");

                b.Property<int>("AbsenceId");

                b.Property<int>("DaysCount");

                b.Property<DateTime>("EndDate");

                b.Property<int>("Id");

                b.Property<bool>("IsAccepted");

                b.Property<DateTime>("StartDate");

                b.HasKey("UserId", "AbsenceId");

                b.HasIndex("AbsenceId");

                b.ToTable("TakenAbsences");
            });

            modelBuilder.Entity("Callendar.Task", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<bool>("IsClosed");

                b.Property<int>("TaskCategoryId");

                b.Property<Guid>("UserId");

                b.HasKey("Id");

                b.HasIndex("TaskCategoryId");

                b.HasIndex("UserId");

                b.ToTable("Tasks");
            });

            modelBuilder.Entity("Callendar.TaskCategory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description");

                b.Property<string>("Name");

                b.Property<int>("ScorePoints");

                b.HasKey("Id");

                b.ToTable("TaskCategories");
            });

            modelBuilder.Entity("Callendar.Team", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Teams");
            });

            modelBuilder.Entity("Callendar.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Email");

                b.Property<string>("FirstName");

                b.Property<string>("LastName");

                b.Property<string>("Password");

                b.Property<string>("PhotoPath");

                b.Property<int>("Points");

                b.Property<int>("PositionId");

                b.Property<int>("TeamId");

                b.Property<int>("VacationDaysLeft");

                b.HasKey("Id");

                b.HasIndex("PositionId");

                b.HasIndex("TeamId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Callendar.TakenAbsence", b =>
            {
                b.HasOne("Callendar.Absence", "Absence")
                    .WithMany("TakenAbsences")
                    .HasForeignKey("AbsenceId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Callendar.User", "User")
                    .WithMany("TakenAbsences")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Callendar.Task", b =>
            {
                b.HasOne("Callendar.TaskCategory", "TaskCategory")
                    .WithMany("Tasks")
                    .HasForeignKey("TaskCategoryId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Callendar.User", "User")
                    .WithMany("Tasks")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Callendar.User", b =>
            {
                b.HasOne("Callendar.Position", "Position")
                    .WithMany("Users")
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Callendar.Team", "Team")
                    .WithMany("Users")
                    .HasForeignKey("TeamId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}